NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/x3d-s_clipgcn_tensor_cs_70_10_20_182'
TRAIN:
  MAX_ITER: 12000
  LOG_STEP: 10
  SAVE_STEP: 500
  EVAL_STEP: 500
  RESUME: False
  USE_TENSORBOARD: True
  MIXED_PRECISION: True
TEST:
  CHECKPOINT: 'outputs/x3d-s_clipgcn_tensor_cs_70_10_20_182/model_final.pth'
  OUTPUT_DIR: 'outputs/x3d-s_clipgcn_tensor_cs_70_10_20_182/test'
  SPLIT: 'test'
DATASETS:
  MODALITY: 'RGB'
  TYPE: 'TensorClip'
  SAMPLE_STRATEGY: 'DenseSample'
  CLIP_LEN: 1
  FRAME_INTERVAL: 6
  NUM_CLIPS: 13
  NUM_SAMPLE_POSITIONS: 1
  TRAIN:
    NAME: 'CLIPGCN_TENSOR'
    DATA_DIR: 'data/clipgcn_tensor_cs_70_10_20'
    ANNOTATION_DIR: 'data/clipgcn_tensor_cs_70_10_20'
    SPLIT: 1
  TEST:
    NAME: 'CLIPGCN_TENSOR'
    DATA_DIR: 'data/clipgcn_tensor_cs_70_10_20'
    ANNOTATION_DIR: 'data/clipgcn_tensor_cs_70_10_20'
    SPLIT: 1
    SPLIT_NAME: 'val'
TRANSFORM:
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  TRAIN:
    SCALE_JITTER: (182, 228)
    RANDOM_HORIZONTAL_FLIP: True
    COLOR_JITTER: (0.1, 0.1, 0.1, 0.1)
    RANDOM_ROTATION: 10
    RANDOM_CROP: True
    CENTER_CROP: False
    TRAIN_CROP_SIZE: 182
    RANDOM_ERASING: True
    TENSOR_AUGMENTATION: True
    TENSOR_CROP_SCALE: (0.70, 1.0)
    TENSOR_CROP_RATIO: (0.85, 1.15)
    TENSOR_ERASING_PROB: 0.25
    TENSOR_NOISE_STD: 0.01
    TENSOR_RESIZE_SIZE: 182
  TEST:
    SHORTER_SIDE: 182
    CENTER_CROP: True
    THREE_CROP: False
    TEST_CROP_SIZE: 182
    TENSOR_RESIZE_SIZE: 182
DATALOADER:
  TRAIN_BATCH_SIZE: 64
  TEST_BATCH_SIZE: 64
  NUM_WORKERS: 16
  PERSISTENT_WORKERS: True
  PREFETCH_FACTOR: 4
MODEL:
  NAME: 'X3D_S'
  PRETRAINED: 'pretrained/x3d_s.pyth'
  SYNC_BN: False
  CONV_LAYER: 'Conv3d'
  POOL_LAYER: 'MaxPool3d'
  NORM_LAYER: 'BatchNorm3d'
  ACT_LAYER: 'ReLU'
  BACKBONE:
    NAME: 'X3D'
    IN_CHANNELS: 3
    PARTIAL_BN: False
    TORCHVISION_PRETRAINED: False
    ZERO_INIT_RESIDUAL: True
    BASE_CHANNEL: 24
    CONV1_KERNEL: (3, 3, 3)
    CONV1_STRIDE: (1, 2, 2)
    CONV1_PADDING: (1, 1, 1)
    WITH_POOL1: False
    WITH_POOL2: False
    STAGE_BLOCKS: (3, 5, 11, 7)
    RES_PLANES: (54, 108, 216, 432)
    EXPANSION: 0.445
    SPATIAL_STRIDES: (2, 2, 2, 2)
    INFLATES: (1,1,1,1)
    INFLATE_STYLE: '3x3x3'
  HEAD:
    NAME: 'X3DHead'
    FEATURE_DIMS: 192
    DROPOUT: 0.5
    NUM_CLASSES: 55
    CONV5_CHANNELS: 432
    POOL5_KERNEL: (13, 5, 5)
  RECOGNIZER:
    NAME: 'OfficialX3DRecognizer'
  CONSENSU:
    NAME: 'AvgConsensus'
  CRITERION:
    NAME: 'CrossEntropyLoss'
    LABEL_SMOOTHING: 0.1
OPTIMIZER:
  NAME: 'SGD'
  LR: 1e-3
  WEIGHT_DECAY: 1e-4
  SGD:
    MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  GAMMA: 0.1
  MULTISTEP_LR:
    MILESTONES: [ 6000, 10000 ]
  WARMUP:
    ITERATION: 400
    MULTIPLIER: 1.0
